<ul>
	<li>1.0.10
	<br>
	BR #12528 Navigator doesn't clear excluded prefixes in some situations
	</li>
	<li>1.0.9 (again)
	<br>
	BR #12456 - Navigator breadcrumbs with default page hidden from menu causes PHP notice.
	</li>
	<li>1.0.9
	<br>
	Template fix simple_navigation.tpl. Output correct class for parent without active children.
	</li>
	<li>1.0.8 
	<br>
	Minor english documentation correction.
	</li>
	<li>1.0.7
	<br>
	Adds a __get() method to the NavigatorNode class to squash some error notices.
	</li>
	<li>1.0.5
	<ul>
	<li>Minor optimizations.</li>
	<li>Use pageid in calculations of cacheid.</li>
	<li>Output template help to Navigator.</li>
	</ul>
	</li>
	<li>1.0.3
	<br>
	Improved exception handling on install
	</li>
	<li>1.0.1
	<ul>
	<li>Changes to createSmartyTemplate calls.</li>
	<li>Minor change to the help ($node->children_exist)</li>
	</ul>
	</li>
	<li>Initial release 2014</li>
</ul>
