<?php
# CMS Made Simple class CMS_Content_Block
# (c) 2004 CMS Made Simple Foundation Inc <foundation@cmsmadesimple.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# BUT withOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#$Id$

/*
NOTE the API for handling {content*} tags is deficient in that it does not
support use of such tags having display-time-specified parameter values e.g.
inside a {foreach} block in a template.
In such cases, the blocks would be processed as expected in frontend pages, but
cannot be accessed in ContentManager admin actions because those rely on methods
in the insuficient page_template_parser class, and here, bogus property-values
can be recorded.
Not readily fixed ...
*/
/**
 * Helper class to deal with parsing or fetching content blocks.
 *
 * @author      Robert Campbell
 * @since       1.11
 * @ignore
 * @internal
 * @package     CMS
 */
final class CMS_Content_Block
{
    private static $_priority;
    private static $_contentBlocks; // cache of blocks' parameters, retrieved by Content::get_content_blocks()
    private static $_primary_content; // generated by preprocess_mact
    private static $_primary_content_flag; // indicates that content has been generated once, do not repeat
    private function __construct() {}

    // $smarty is a Template object, not the global Smarty instance
    private static function content_return($result,$params,$smarty)
    {
        if ( !empty($params['assign']) ) {
            $smarty->assign(trim($params['assign']),$result);
        }
        else {
            echo $result;
        }
    }

    public static function has_primary_content()
    {
        return self::$_primary_content_flag;
    }

    public static function set_primary_content($txt)
    {
        self::$_primary_content = $txt;
        self::$_primary_content_flag = 1;
    }

    public static function get_content_blocks()
    {
        return self::$_contentBlocks;
    }

    public static function reset()
    {
        self::$_priority = 100;
        self::$_contentBlocks = null; // aka unset
    }

    // Cache properties of a {content} tag
    // todo: could be in page_template_parser
    public static function smarty_compiler_contentblock($params,$compiler)
    {
        $rec = array('type'=>'text','id'=>'','name'=>'','noedit'=>false,'usewysiwyg'=>'true','oneline'=>'false','default'=>'','label'=>'',
                     'size'=>'50','tab'=>'','maxlength'=>'255','required'=>0,'placeholder'=>'','priority'=>'','cssname'=>'','adminonly'=>0);
        foreach( $params as $key => $value ) {
            $value = trim($value,'"\'');
            if( $key == 'type' ) continue;
            if( startswith($key,'data-') ) {
                $rec[$key] = $value;
                continue;
            }
            if( $key == 'block' ) $key = 'name';
            if( $key == 'wysiwyg' ) $key = 'usewysiwyg';
            if( isset($rec[$key]) ) $rec[$key] = $value;
        }

        if( !$rec['name'] ) $rec['name'] = $rec['id'] = 'content_en';
        if( strpos($rec['name'],' ') !== false ) {
            if( !$rec['label'] ) $rec['label'] = $rec['name'];
            $rec['name'] = str_replace(' ','_',$rec['name']);
        }
        if( !$rec['id'] ) $rec['id'] = str_replace(' ','_',$rec['name']);

        if( !isset(self::$_contentBlocks) ) { self::$_contentBlocks = array(); }
        // check for duplicate
        elseif( isset(self::$_contentBlocks[$rec['name']]) ) { throw new CmsEditContentException('Duplicate content block: '.$rec['name']); }

        // ensure a priority
        if( !$rec['priority'] ) {
            if( !self::$_priority ) self::$_priority = 100;
            $rec['priority'] = self::$_priority++;
        }

        self::$_contentBlocks[$rec['name']] = $rec;
    }

    // Cache properties of a {content_image} tag
    // todo: could be in page_template_parser
    public static function smarty_compiler_imageblock($params,$compiler)
    {
        if( empty($params['block']) ) throw new CmsEditContentException('{content_image} tag requires block parameter');

        $rec = [ 'type'=>'image','name'=>'','label'=>'','upload'=>true,'dir'=>'','default'=>'','tab'=>'',
                 'priority'=>'','exclude'=>'','sort'=>0,'profile'=>'' ];
        foreach( $params as $key => $value ) {
            if( $key == 'type' ) continue;
            if( $key == 'block' ) $key = 'name';
            if( isset($rec[$key]) ) $rec[$key] = trim($value,"'\""); //TODO handle compiler content e.g. "A".stuff
        }

        if( !$rec['name'] ) {
            $n = count(self::$_contentBlocks)+1;
            $rec['name'] = 'image_'+$n;
        }
        if( strpos($rec['name'],' ') !== FALSE ) {
            if( !$rec['label'] ) $rec['label'] = $rec['name'];
            $rec['name'] = str_replace(' ','_',$rec['name']);
        }
        if( empty($rec['id']) ) $rec['id'] = str_replace(' ','_',$rec['name']);
        if( !$rec['priority'] ) {
            if( !self::$_priority ) self::$_priority = 100;
            $rec['priority'] = self::$_priority++;
        }

        if( !isset(self::$_contentBlocks) ) { self::$_contentBlocks = array(); }
        // check for duplicate
        elseif( isset(self::$_contentBlocks[$rec['name']]) ) { throw new CmsEditContentException('Duplicate content block: '.$rec['name']); }

        // ensure a priority
        if( empty($rec['priority']) || $rec['priority'] == 0 ) {
            if( !self::$_priority ) self::$_priority = 100;
            $rec['priority'] = self::$_priority++;
        }

        self::$_contentBlocks[$rec['name']] = $rec;
    }

    // Cache properties of a {content_module} tag
    // todo: could be in page_template_parser
    public static function smarty_compiler_moduleblock($params,$compiler)
    {
        if( !isset($params['block']) || empty($params['block']) ) throw new CmsEditContentException('{content_module} tag requires block parameter');

        $rec = array('type'=>'module','id'=>'','name'=>'','module'=>'','label'=>'','blocktype'=>'','tab'=>'','priority'=>'');
        $parms = array();
        foreach( $params as $key => $value ) {
            if( $key == 'block' ) $key = 'name';

            $value = trim(trim($value,'"\'')); //TODO handle compiler content e.g. "A".stuff
            if( $key != 'type' && isset($rec[$key]) ) { // a provided 'type' is for the handler
                $rec[$key] = $value;
            }
            else {
                $parms[$key] = $value;
            }
        }

        if( !$rec['name'] ) {
            $n = count(self::$_contentBlocks)+1;
            $rec['id'] = $rec['name'] = 'module_'+$n;
        }
        if( strpos($rec['name'],' ') !== FALSE ) {
            if( !$rec['label'] ) $rec['label'] = $rec['name'];
            $rec['name'] = str_replace(' ','_',$rec['name']);
        }
        if( !$rec['id'] ) $rec['id'] = str_replace(' ','_',$rec['name']);
        $rec['params'] = $parms;
        if( $rec['module'] == '' ) throw new CmsEditContentException('Missing module param for content_module tag');
        if( !$rec['priority'] ) {
            if( !self::$_priority ) self::$_priority = 100;
            $rec['priority'] = self::$_priority++;
        }

        if( !isset(self::$_contentBlocks) ) { self::$_contentBlocks = array(); }
        // check for duplicate
        elseif( isset(self::$_contentBlocks[$rec['name']]) ) { throw new CmsEditContentException('Duplicate content block: '.$rec['name']); }

        // ensure a priority
        if( !$rec['priority'] ) {
            if( !self::$_priority ) self::$_priority = 100;
            $rec['priority'] = self::$_priority++;
        }

        self::$_contentBlocks[$rec['name']] = $rec;
    }

    // Compile a {content} tag for frontend use
    public static function smarty_compile_fecontentblock($params,$compiler)
    {
        $ptext = 'array(';
        $tmp = array();
        foreach($params as $k => $v) {
            $tmp[] .= '\''.$k.'\'=>'.$v;
        }
        $ptext .= implode(',',$tmp);
        $ptext .= ')';
        return '<?php CMS_Content_Block::smarty_internal_fetch_contentblock('.$ptext.', $_smarty_tpl); ?>';
    }

    // Frontend {content} plugin handler
    // per smarty_compile_fecontentblock()
    public static function smarty_internal_fetch_contentblock($params,$template)
    {
        $result = '';
        $contentobj = CmsApp::get_instance()->get_content_object();
        if (is_object($contentobj)) {
            if( !$contentobj->IsPermitted() ) throw new CmsError403Exception();
            $id = '';
            $modulename = '';
            $action = '';
            $inline = false;
            $assign = (isset($params['assign'])) ? trim($params['assign']) : ''; //UNUSED
            if (isset($_REQUEST['mact'])) {
                $ary = explode(',',cms_htmlentities($_REQUEST['mact']),4);
                $modulename = ($ary[0])?:'';
                $id = (!empty($ary[1])?$ary[1]:'');
                $action = (!empty($ary[2])?$ary[2]:'');
                $inline = !empty($ary[3]);
            }

            //Only consider doing module processing if
            //a. There is no block parameter
            //b. then
            //   1. $id is cntnt01
            //   2. or inline is false

            $block = (isset($params['block']))?$params['block']:'content_en';
            if ($block == 'content_en' && ($id == 'cntnt01' || $id == '_preview_' || ($id != '' && $inline == false))) {
                if( self::$_primary_content_flag ) {
                    $result = self::$_primary_content;
                }
                else {
                    $modops = ModuleOperations::get_instance();
                    $modobj = $modops->get_module_instance($modulename);
                    if( !$modobj ) {
                        // module not found... couldn't even autoload it.
                        @trigger_error('Attempt to access module '.$modulename.' which could not be found (is it properly installed and configured?');
                        throw new \CmsError404Exception('Attempt to access module '.$modulename.' which could not be found (is it properly installed and configured?');
                    }

                    if (!$modobj->IsPluginModule() ) {
                        @trigger_error('Attempt to access module '.$modulename.' which could not be found (is it properly installed and configured?');
                        self::content_return("<!-- Not a tag module -->\n",$params,$template);
                        return '';
                    }

                    $parms = [];
                    foreach( $params as $key => $value ) {
                        switch( $key ) {
                        case 'block':
                        case 'label':
                        case 'wysiwyg':
                        case 'oneline':
                        case 'default':
                        case 'size':
                        case 'cssname':
                        case 'tab':
                        case 'required':
                        case 'priority':
                        case 'placeholder':
                        case 'assign':
                        case 'adminonly':
                            break;
                        default:
                            if( startswith($key,'data-') ) break;
                            $parms[$key] = $value;
                        }
                    }
                    $parms = array_merge($parms,$modops->GetModuleParameters($id));
                    $returnid = $contentobj->Id();
                    if (isset($parms['returnid'])) $returnid = $parms['returnid'];

                    $oldcache = $template->caching;
                    $template->caching = Smarty::CACHING_OFF;
                    @ob_start();
                    $result = $modobj->DoActionBase($action,$id,$parms,$returnid,$template);
                    $template->caching = $oldcache;

                    if( $result !== FALSE ) echo $result;
                    $result = @ob_get_clean();
                }
                self::$_primary_content_flag = true;
            }
            else {
                $result = '';

                $oldvalue = $template->caching;
                $template->caching = Smarty::CACHING_OFF;
                if( isset($_SESSION['__cms_preview__']) && $contentobj->Id() == __CMS_PREVIEW_PAGE__ ) {
                    // note: content precompile/postcompile events will not be triggered in preview.
                    //$val = $contentobj->Show($block);
                    //$result = $template->fetch('eval:'.$val);
                    $result = $template->fetch(str_replace(' ','_','content:' . $block),'|'.$block,$contentobj->Id().$block);
                }
                else {
                    $result = $template->fetch(str_replace(' ','_','content:' . $block),'|'.$block,$contentobj->Id().$block);
                }
                $template->caching = $oldvalue;
            }
        }
        self::content_return($result,$params,$template);
        return '';
    }

    // {process_pagedata} plugin handler
    public static function smarty_fetch_pagedata($params,$template)
    {
        $contentobj = CmsApp::get_instance()->get_content_object();
        if( !is_object($contentobj) || $contentobj->Id() <= 0 ) {
            self::content_return('',$params,$template);
            return '';
        }

        $result = $template->fetch('content:pagedata','',$contentobj->Id());
        if( isset($params['assign']) ){
            $template->assign(trim($params['assign']),$result);
            return '';
        }
        return $result;
    }

    // {content_image} plugin handler
    public static function smarty_fetch_imageblock($params,$template)
    {
        $contentobj = CmsApp::get_instance()->get_content_object();
        if( !is_object($contentobj) || $contentobj->Id() <= 0 ) {
            self::content_return('',$params,$template);
            return '';
        }
        $config = \cms_config::get_instance();
        $dir = $config['uploads_path']; //TODO also support $config['image_uploads_path']
        $basename = basename($dir);

        if( !empty($params['dir']) ) {
            $adddir = strtr($params['dir'],'\\/',DIRECTORY_SEPARATOR.DIRECTORY_SEPARATOR); // maybe the non-native separator was recorded
        }
        else {
            $adddir = \cms_siteprefs::get('contentimage_path');
        }
        if( $adddir ) {
            $dir .= DIRECTORY_SEPARATOR . trim($adddir,' \\/');
        }

        $result = '';
        if( isset($params['block']) ) {
            $oldvalue = $template->caching;
            $template->caching = Smarty::CACHING_OFF;
            $result = $template->fetch(str_replace(' ','_','content:' . $params['block']),'|'.$params['block'],$contentobj->Id().$params['block']);
            $template->caching = $oldvalue;
        }
        $img = $result;

        $out = '';
        if( startswith(realpath($dir),realpath($basename)) ) {
            if( (!$img || $img == -1) && !empty($params['default']) ) {
                $img = $params['default'];
            }
            if( $img && $img != -1 ) {
                // create absolute url.
                if( $img[0] == '/' ) {
                    $img = CMS_ROOT_URL . $img;
                }
                else {
                    $tmp = $config['uploads_url']; //TODO also support $config['image_uploads_url']
//                    if( $adddir ) {
//                        $tmp .= '/' . strtr($adddir,'\\','/');
//                    }
                    $img = $tmp . '/' . $img;
                }

                $urlonly = cms_to_bool(get_parameter_value($params,'urlonly'));
                if( $urlonly ) {
                    $out = $img;
                }
                else {
                    $ignored = [ 'block','type','name','label','upload','dir','default','tab','priority','exclude','sort','profile','urlonly','assign' ];
                    $tagparms = [];
                    foreach( $params as $key => $val ) {
                        $key = trim($key);
                        if( !$key ) continue;
                        $val = trim($val);
                        if( !$val ) continue;
                        if( in_array($key,$ignored) ) continue;
                        $tagparms[$key] = $val;
                    }

                    $out = "<img src=\"$img\"";
                    foreach( $tagparms as $key => $val ) {
                        $out .= " $key=\"$val\"";
                    }
                    $out .= '>';
                }
            }
        }

        if( isset($params['assign']) ){
            $template->assign(trim($params['assign']),$out);
            return '';
        }
        return $out;
    }

    // {content_module} plugin handler
    public static function smarty_fetch_moduleblock($params,$template)
    {
        $result = '';
        if( !empty($params['block']) ) {
            $content_obj = CmsApp::get_instance()->get_content_object();
            if( is_object($content_obj) ) {
                $block = $params['block'];
                $result = $content_obj->GetPropertyValue($block);
                if( $result == -1 ) $result = '';
                $module = isset($params['module']) ? trim($params['module']) : '';
                if( $module ) {
                    $mod = cms_utils::get_module($module);
                    if( is_object($mod) ) $result = $mod->RenderContentBlockField($block,$result,$params,$content_obj);
                }
            }
        }

        if( isset($params['assign']) ) {
            $template->assign(trim($params['assign']),$result);
            return '';
        }
        return $result;
    }
} // end of class

?>
