<?php
#CMS Made Simple class Events
#(c) 2004 CMS Made Simple Foundation Inc <foundation@cmsmadesimple.org>
#
#This program is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 2 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#$Id$

/**
 * Class for handling and dispatching system and user defined events.
 *
 * @package CMS
 * @license GPL
 */
final class Events
{
	/**
	 * @ignore
	 */
	private static $_handlercache;

	/**
	 * @ignore
	 */
	private function __construct() {}

	/**
	 * Inform the system about a new event that can be generated.
	 *
	 * @param string $originator The name of the module (or 'Core') that is sending the event
	 * @param string $eventname The name of the event
	 */
	public static function CreateEvent( $originator, $eventname )
	{
		$db = CmsApp::get_instance()->GetDb();
		$dup = $db->GetOne('SELECT EXISTS(SELECT 1 FROM '.CMS_DB_PREFIX.
		'events WHERE originator = ? AND event_name = ?)', array($originator, $eventname));
		if( $dup == 0 ) {
			$id = $db->GenID( CMS_DB_PREFIX."events_seq" );
			$q = "INSERT INTO ".CMS_DB_PREFIX."events (originator,event_name,event_id) values (?,?,?)";
			$db->Execute( $q, array( $originator, $eventname, $id ));
			\CMSMS\internal\global_cache::clear(__CLASS__);
		}
	}


	/**
	 * Remove a specified event.
	 * This function removes all handlers of the event, and removes
	 * all references to this event, from the database
	 *
	 * @param string $originator The name of the module that originates the event
	 * @param string $eventname The name of the event
	 */
	public static function RemoveEvent($originator, $eventname)
	{
		$db = CmsApp::get_instance()->GetDb();

		// get the id
		$q = 'SELECT event_id FROM '.CMS_DB_PREFIX.
		'events WHERE originator = ? AND event_name = ?';
		$id = $db->GetOne($q, array($originator, $eventname));
		if( !$id ) {
			// query failed, event not found
			return false;
		}

		// delete all handlers
		$q = "DELETE FROM ".CMS_DB_PREFIX."event_handlers WHERE event_id = ?";
		$db->Execute( $q, array( $id ) );

		// delete the event
		$q = "DELETE FROM ".CMS_DB_PREFIX."events WHERE event_id = ?";
		$db->Execute( $q, array( $id ) );

		\CMSMS\internal\global_cache::clear(__CLASS__);
	}


	/**
	 * Trigger an event.
	 * This function will call all registered event handlers for the event
	 *
	 * @param string $originator The name of the module sending the event or 'Core'
	 * @param string $eventname The name of the event
	 * @param array $params Optional parameters associated with this event. Default empty
	 */
	public static function SendEvent($originator, $eventname, $params = array())
	{
		global $CMS_INSTALL_PAGE;
		if( isset($CMS_INSTALL_PAGE) ) return;

		$results = self::ListEventHandlers($originator, $eventname);

		if( $results ) {
			$params['_modulename'] = $originator;
			$params['_eventname'] = $eventname;
			foreach( $results as $row ) {
				if( !empty( $row['tag_name']) ) {
					debug_buffer('calling user tag ' . $row['tag_name'] . ' from event ' . $eventname);
					if( !isset($usertagops) ) {
						$gCms = CmsApp::get_instance();
						$usertagops = $gCms->GetUserTagOperations();
					}
					$usertagops->CallUserTag($row['tag_name'], $params);
				}
				elseif( !empty($row['module_name']) ) {
					// don't call the module DoEvent function for an event
					// originated by the same module
					if( $row['module_name'] == $originator ) continue;
					// call the module event handler.
					$obj = CMSModule::GetModuleInstance($row['module_name']);
					if( $obj ) {
						debug_buffer('calling module ' . $row['module_name'] . ' from event ' . $eventname);
						$obj->DoEvent($originator, $eventname, $params);
					}
				}
			}
		}
	}


	/**
	 * Initiate the events-data cache
	 * @ignore
	 */
	public static function setup()
	{
		$obj = new \CMSMS\internal\global_cachable(__CLASS__,function() {
				$db = \CmsApp::get_instance()->GetDb();
				$q = "SELECT e.event_id, eh.tag_name, eh.module_name, e.originator, e.event_name, eh.handler_order, eh.handler_id, eh.removable
FROM ".CMS_DB_PREFIX."event_handlers eh
INNER JOIN ".CMS_DB_PREFIX."events e ON e.event_id = eh.event_id
ORDER BY eh.handler_order ASC";
				return $db->GetArray($q);//TODO replace null string-field values with ''
		});
		\CMSMS\internal\global_cache::add_cachable($obj);
	}

	/**
	 * Get the cached event-data for the specified event generated by the specified module.
	 *
	 * @param string $originator The name of the module sending the event or 'Core'
	 * @param string $eventname The name of the event
	 * @return array Empty or having members each of which is an array
	 *               See particulars in Events::setup()

	 */
	public static function ListEventHandlers($originator, $eventname)
	{
		$handlers = array();

		self::$_handlercache = \CMSMS\internal\global_cache::get(__CLASS__);
		if( is_array(self::$_handlercache) && count(self::$_handlercache) ) {
			foreach (self::$_handlercache as $row) {
				if ($row['originator'] == $originator && $row['event_name'] == $eventname) $handlers[] = $row;
			}
		}

		return $handlers;
	}


	/**
	 * Get the cached event-data for a particular event.
	 *
	 * @param int $handler_id numeric id of the event handler
	 * @return array maybe empty
	 */
	public static function GetEventHandler($handler_id)
	{
		self::$_handlercache = \CMSMS\internal\global_cache::get(__CLASS__);

		if( is_array(self::$_handlercache) && count(self::$_handlercache) ) {
			foreach( self::$_handlercache as $row ) {
				if( $row['handler_id'] == $handler_id ) return $row;
			}
		}
		return [];
	}

	/**
	 * Get all usable events.
	 *
	 * @return array Events-data or empty
	 */
	public static function ListEvents()
	{
		$db = CmsApp::get_instance()->GetDb();

		//None of these string-fields may be null-valued
		$q = 'SELECT e.originator, e.event_name, e.event_id, COUNT(eh.event_id) AS usage_count FROM '.CMS_DB_PREFIX.
'events e LEFT JOIN '.CMS_DB_PREFIX.
'event_handlers eh ON e.event_id=eh.event_id GROUP BY e.originator, e.event_name, e.event_id ORDER BY originator,event_name';

		$dbresult = $db->Execute( $q );
		if( $dbresult == false ) return [];

		$result = array();
		while( $row = $dbresult->FetchRow() ) {
			if( $row['originator'] == 'Core' || cms_utils::module_available($row['originator']) ) {
				$result[] = $row;
			}
		}
		$dbresult->Close();
		return $result;
	}


	/**
	 * Add a handler for an event.
	 * Either $tag_name or $module_handler (but not both) must be specified
	 *
	 * @param string $originator The name of the module sending the event or 'Core'
	 * @param string $eventname The name of the event
	 * @param string $tag_name Optional name of a user defined tag to handle the event. Default ''.
	 * @param string $module_handler Optional name of a module to handle the event. Default ''.
	 * @param bool $removable Optional flag whether this event can be removed. Default true.
	 * @return bool indicating success.
	 */
	public static function AddEventHandler( $originator, $eventname, $tag_name = '', $module_handler = '', $removable = true)
	{
		if( !$tag_name && !$module_handler ) return false;
		if( $tag_name && $module_handler ) return false;

		$db = CmsApp::get_instance()->GetDb();

		// find the id
		$q = "SELECT event_id FROM ".CMS_DB_PREFIX.
		"events WHERE originator = ? AND event_name = ?";
		$dbresult = $db->Execute( $q, array( $originator, $eventname ) );
		if( $dbresult == false || $dbresult->RecordCount() == 0 ) return false; // query failed, event not found
		$row = $dbresult->FetchRow();
		$id = $row['event_id'];

		// now see if there's nothing already existing for this
		// tag or module and this id
		$q = "SELECT * FROM ".CMS_DB_PREFIX."event_handlers WHERE event_id = ? AND ";
		$params = array();
		$params[] = $id;
		if( $tag_name != '' ) {
			$q .= "tag_name = ?";
			$params[] = $tag_name;
		}
		else {
			$q .= "module_name = ?";
			$params[] = $module_handler;
		}
		$dbresult = $db->Execute( $q, $params );
		if( $dbresult != false && $dbresult->RecordCount() > 0 ) return false; // hmmm, something matches already

		// now see if we can get a new id
		$order = 1;
		$q = "SELECT max(handler_order) AS newid FROM ".CMS_DB_PREFIX.
		"event_handlers WHERE event_id = ?";
		$dbresult = $db->Execute( $q, array( $id ) );
		if( $dbresult != false && $dbresult->RecordCount() != 0) {
			$row = $dbresult->FetchRow();
			$order = $row['newid'] + 1;
		}

		$handler_id = $db->GenID( CMS_DB_PREFIX."event_handler_seq" );

		// okay, we can insert
		$params = array();
		$params[] = $id;
		$q = "INSERT INTO ".CMS_DB_PREFIX."event_handlers ";
		if( $module_handler != false ) {
			$q .= '(event_id,module_name,removable,handler_order,handler_id)';
			$params[] = $module_handler;
		}
		else {
			$q .= '(event_id,tag_name,removable,handler_order,handler_id)';
			$params[] = $tag_name;
		}
		$q .= "VALUES (?,?,?,?,?)";
		$params[] = ($removable?1:0);
		$params[] = $order;
		$params[] = $handler_id;
		$dbresult = $db->Execute( $q, $params );
		\CMSMS\internal\global_cache::clear(__CLASS__);
		if( $dbresult != false ) return true;
		return false;
	}

	/**
	 * @ignore
	 */
	protected static function InternalRemoveHandler( array $handler )
	{
		$db = CmsApp::get_instance()->GetDb();
		$id = $handler['event_id'];

		// update any subsequent handlers
		$sql = 'UPDATE '.CMS_DB_PREFIX.'event_handlers SET handler_order = handler_order - 1 WHERE event_id = ? AND handler_order > ?';
		$db->Execute( $sql, [ $id, $handler['handler_order']] );

		// now delete this record
		$sql = 'DELETE FROM '.CMS_DB_PREFIX.'event_handlers WHERE event_id = ? AND handler_id = ?';
		$db->Execute( $sql, [ $id, $handler['handler_id']  ] );

		\CMSMS\internal\global_cache::clear(__CLASS__);
	}

	/**
	 * Remove a specific event handler
	 *
	 * @param int $handler_id
	 */
	public static function RemoveEventHandlerById($handler_id)
	{
		$handler = self::GetEventHandler($handler_id);
		if( $handler ) self::InternalRemoveHandler($handler);
	}

	/**
	 * Remove handlers of a specific event
	 * It is an error to specify both $tag_name and $module_handler
	 *
	 * @param string $originator The name of the module sending the event or 'Core'
	 * @param string $eventname The name of the event
	 * @param string $tag_name Optional name of a user defined tag. Default ''
	 * @param string $module_handler Optional name of the module. Default ''.
	 * @return bool indicating success
	 */
	public static function RemoveEventHandler($originator, $eventname, $tag_name = '', $module_handler = '')
	{
		if( $tag_name && $module_handler ) return false;
		$field = 'handler_name';
		if( $module_handler ) $field = 'module_handler';

		$db = CmsApp::get_instance()->GetDb();

		// find the event id
		$sql = "SELECT event_id FROM ".CMS_DB_PREFIX."events WHERE originator = ? AND event_name = ?";
		$id = (int) $db->GetOne( $sql, [ $originator, $eventname ] );
		if( $id < 1 ) {
			// query failed, event not found
			return false;
		}

		// find the handler
		$sql = 'SELECT * FROM '.CMS_DB_PREFIX.'event_handlers WHERE event_id = ? AND ';
		$params = [ $id ];
		if( $module_handler != false ) {
			$sql .= 'module_name = ?';
			$params[] = $module_handler;
		}
		else {
			$sql .= 'tag_name = ?';
			$params[] = $tag_name;
		}
		$row = $db->GetRow( $sql, $params );
		if( !is_array($row) || !count($row) ) return false;

		self::InternalRemoveHandler( $row );
		return true;
	}


	/**
	 * Clears all the event handlers for the given event.
	 *
	 * @param string $originator The name of the module sending the event or 'Core'
	 * @param string $eventname The name of the event
	 * @return bool If successful, true.  If it fails, false.
	 */
	public static function RemoveAllEventHandlers( $originator, $eventname )
	{
		$db = CmsApp::get_instance()->GetDb();

		// find the id
		$q = "SELECT event_id FROM ".CMS_DB_PREFIX.
		"events WHERE originator = ? AND event_name = ?";
		$dbresult = $db->Execute( $q, array( $originator, $eventname ) );
		if( $dbresult == false || $dbresult->RecordCount() == 0 ) {
			// query failed, event not found
			return false;
		}
		$row = $dbresult->FetchRow();
		$id = $row['event_id'];

		// and delete the handlers
		$q = "DELETE FROM ".CMS_DB_PREFIX."event_handlers WHERE event_id = ?";
		$dbresult = $db->Execute( $q, array( $id ) );
		\CMSMS\internal\global_cache::clear(__CLASS__);
		if( $dbresult == false ) return true;
		return false;
	}


	/**
	 * Move an event handler (by id) up in its event...
	 *
	 * @param int $handler_id
	 */
	public static function OrderHandlerUp( $handler_id )
	{
		$handler = self::GetEventHandler( $handler_id );
		if( !$handler ) return;

		if( $handler['handler_order'] < 2 ) return;

		$db = CmsApp::get_instance()->GetDb();
		$sql = 'UPDATE '.CMS_DB_PREFIX.'event_handlers SET handler_order = handler_order + 1 WHERE event_id = ? AND handler_order = ?';
		$db->Execute( $sql, [ $handler['event_id'], $handler['handler_order'] - 1 ] );
		$sql = 'UPDATE '.CMS_DB_PREFIX.'event_handlers SET handler_order = handler_order - 1 WHERE event_id = ? AND handler_id = ?';
		$db->Execute( $sql, [ $handler['event_id'], $handler['handler_id'] ] );
		\CMSMS\internal\global_cache::clear(__CLASS__);
	}

	/**
	 * Move an event handler (by id) down in its event...
	 *
	 * @param int $handler_id
	 */
	public static function OrderHandlerDown( $handler_id )
	{
		$handler = self::GetEventHandler( $handler_id );
		if( !$handler ) return;

		$db = CmsApp::get_instance()->GetDb();
		$sql = 'UPDATE '.CMS_DB_PREFIX.'event_handlers SET handler_order = handler_order - 1 WHERE event_id = ? AND handler_order = ?';
		$db->Execute( $sql, [ $handler['event_id'], $handler['handler_order'] + 1 ] );
		$sql = 'UPDATE '.CMS_DB_PREFIX.'event_handlers SET handler_order = handler_order + 1 WHERE event_id = ? AND handler_id = ?';
		$db->Execute( $sql, [ $handler['event_id'], $handler['handler_id'] ] );
		\CMSMS\internal\global_cache::clear(__CLASS__);
	}

	/**
	 * Place to handle the help messages for core events.  Basically just going to
	 * call out to the lang() function.
	 *
	 * @param string $eventname The name of the event
	 * @return string Returns the help string for the event.  Empty string if nothing
	 *                is found.
	 */
	static function GetEventHelp($eventname)
	{
		return lang('event_help_'.strtolower((string)$eventname));
	}


	/**
	 * Place to handle the description strings for core events.  Basically just going to
	 * call out to the lang() function.
	 *
	 * @param string $eventname The name of the event
	 * @return string Returns the description string for the event.  Empty string if nothing
	 *                is found.
	 */
	public static function GetEventDescription($eventname)
	{
		return lang('event_desc_'.strtolower((string)$eventname));
	}
} // class

?>
