[main]
installer_version = "1.4.0";
min_upgrade_version = "1.12.2"
archive = "data/data.tar.gz"
dbtype = "mysqli"
dbhost = "localhost"
dbprefix = "cms_"
;case-sensitive folder-names for themes being installed, or already installed, for demo site content purposes
demothemes[] = "NCleanBlue" 
demothemes[] = "ngrey" 
demothemes[] = "simplex" 
;bundled non-core modules
extramodules[] = "News"
extramodules[] = "UserGuide"
install_excludes = "/find-mime$/||/scripts\/.*$/||/\/svn.*/||/\/tests\/.*/||/\/build\/.*/||/\/tmp\/.*/"
;earliest current-security-supported micro-version, via https://www.php.net/supported-versions.php and https://www.php.net/releases/index.php
livephpmin = "8.1.32"
;relative-path for frontend themes data "" becomes default i.e. assets/themes
themes_dir = ""
