1.0 - September 2015<br>
Initial release<br>
<br>
1.0.1 - April 2016<br>
Minor fix to permissions checks<br>
<br>
1.0.2 - August 2016<br>
Use &apos;Manage Stylesheets&apos; permission when searching stylesheets<br>
<br>
1.0.3 - June 2017<br>
Fix problem with use of &apos;Use Admin Search&apos; permission<br>
Search in templates and stylesheets stored as files<br>
Use HasSearchableContent method when searching content pages<br>
<br>
1.0.4 - July 2017<br>
Search in the metadata field of content pages<br>
Fixes for single quotes in search results<br>
<br>
1.0.5 - March 2020<br>
Remove click-thru warning<br>
<br>
1.0.6 - January 2022<br>
Fixed BR #12443 Admin Search fails on some searches with default mysql mode only_full_group_by (mysql 5.7.5+)<br>
Added option to search case (in)sensitive. (external modules might ignore this)<br>
Added option to show/hide snippets with the results<br>
Added number of occurrences per item (external modules might not show this)<br>
If snippets are enabled all occurrences are shown, and for all searched attributes<br>
If snippets are enabled they are grouped by the 'location' of the match (external modules might not show this)<br>
More attributes of content objects are searched<br>
More types of content object are searched<br>
<br>
1.0.7 - August 2023<br>
FR 12555 Added option to exclude inactive-pages from searches<br>
