1.0.6<br>
=====<br>
<br>
- fixed BR #12443 Admin Search fails on some searches with default mysql mode only_full_group_by (mysql 5.7.5+)<br>
- added option to search case (in)sensitive. (external modules may ignore this)<br>
- added option to show/hide snippets with the results<br>
- added number of occurrences per item (external modules may not show this)<br>
- if snippets are enabled all occurrences are shown, and for all searched attributes<br>
- if snippets are enabled they are grouped by the 'location' of the match (external modules may not show this)<br>
- more attributes of content objects are searched<br>
- more types of content object are searched<br>
