<ul>
<li>2023-MM-DD v1.1.10</li>
 <li>BR #12474 - Taking the default page down by accident through the content type</li>
<li>2023-06-13 v1.1.10</li>
 <li>Differentiate new page from cloned page</li>
<li>2022-01-21 v1.1.9</li>
 <li>Fix menu text/title setting</li>
<li>2020-10-13 v1.1.9</li>
 <li>BR #12313 - 5 stored XSS vulnerabilities in Settings</li>
<li>2020-03-30 v1.1.9
<ul>
 <li>Fix notices in edit content template</li>
 <li>Fix notice in default admin view</li>
</ul>
</li>
<li>2019-09-01 v1.1.8
<ul>
 <li>Fix an issue with copying non-core content objects</li>
 <li>Minor fixes for PHP 7.3</li>
</ul>
</li>
<li>2019-01-19 v1.1.7</li>
 <li>Fix an issue with changing content type after copying a content page</li>
<li>2017-08-26 v1.1.6</li>
 <li>Double check that the 'default parent' for new pages actually exists</li>
<li>2017-06-10 v1.1.5
<ul>
 <li>Minor tweak to bulk delete pages</li>
 <li>Minor fix to the active tab when changing a template or design</li>
 <li>Now listen to the 'default parent page' user preference</li>
 <li>Fix minor XSS problem in the Admin if some loser puts JavaScript into the title field or alias field or menu text field</li>
 <li>Now allow filtering pages by owner, editor, template, or design.  Only for Administrators with Modify any page, or Manage all content permissions</li>
 <li>Fix problems with auto-refresh being too fast for some operations</li>
 <li>Now auto scroll to the first matched page in a find</li>
 <li>Additional editors of a page cannot change the content type. Only owners, or users with the Manage all Content permissions</li>
 <li>Fix a problem with the call to GetTabElements</li>
</ul>
</li>
<li>2016-12-10 v1.1.4
<ul>
 <li>Fix bulk set-non-cachable functionality</li>
 <li>Fix a bug wrt content blocks and the adding flag</li>
</ul>
</li>
<li>2016-08-14 v1.1.1
<ul>
 <li>Improve error handling in Edit Content</li>
 <li>Fix a problem with the call to GetTabElements</li>
</ul>
</li>
<li>2015-12-20 v1.1
<ul>
 <li>Minor template changes in edit content wrt. locking</li>
 <li>Adds ability to clear content locks</li>
 <li>Enhancements to the action to bulk set designs to show only page templates by default, but to optionally show more</li>
</ul>
</li>
<li>2015-12-06 v1.0.2
<ul>
 <li>Fix problem with pagedefault metadata</li>
 <li>Fixes for handling no listable templates for a design</li>
 <li>More work with locking. With only one exception all locking and unlocking is initiated via javascript</li>
 <li>Minor fix to copycontent</li>
</ul>
</li>
<li>2015-09-06 v1.0</li>
 <li>Initial public release</li>
</ul>
