<ul>
<li>2023-MM-DD v1.1.11<br>
 BR #12474 - Taking the default page down by accident through the content type<br>
 BR #12635 - Apply button is shown for non-existing page and creates new pages
</li> 
<li>2023-06-13 v1.1.10<br>
 Differentiate new page from cloned page
</li>
<li>2022-01-21 v1.1.9<br>
 Fix menu text/title setting
</li>
<li>2020-10-13 v1.1.9<br>
 BR #12313 - 5 stored XSS vulnerabilities in Settings
</li>
<li>2020-03-30 v1.1.9<br>
 Fix notices in edit content template<br>
 Fix notice in default admin view
</li>
<li>2019-09-01 v1.1.8<br>
 Fix an issue with copying non-core content objects<br>
 Minor fixes for PHP 7.3
</li>
<li>2019-01-19 v1.1.7<br>
 Fix an issue with changing content type after copying a content page
</li>
<li>2017-08-26 v1.1.6<br>
 Double check that the 'default parent' for new pages actually exists
</li>
<li>2017-06-10 v1.1.5<br>
 Minor tweak to bulk delete pages<br>
 Minor fix to the active tab when changing a template or design<br>
 Now listen to the 'default parent page' user preference<br>
 Fix minor XSS problem in the Admin if some loser puts JavaScript into the title field or alias field or menu text field<br>
 Now allow filtering pages by owner, editor, template, or design.  Only for Administrators with Modify any page, or Manage all content permissions<br>
 Fix problems with auto-refresh being too fast for some operations<br>
 Now auto scroll to the first matched page in a find<br>
 Additional editors of a page cannot change the content type. Only owners, or users with the Manage all Content permissions<br>
 Fix a problem with the call to GetTabElements
</li>
<li>2016-12-10 v1.1.4<br>
 Fix bulk set-non-cachable functionality<br>
 Fix a bug wrt content blocks and the adding flag
</li>
<li>2016-08-14 v1.1.1<br>
 Improve error handling in Edit Content<br>
 Fix a problem with the call to GetTabElements
</li>
<li>2015-12-20 v1.1<br>
 Minor template changes in edit content wrt. locking<br>
 Adds ability to clear content locks<br>
 Enhancements to the action to bulk set designs to show only page templates by default, but to optionally show more
</li>
<li>2015-12-06 v1.0.2<br>
 Fix problem with pagedefault metadata<br>
 Fixes for handling no listable templates for a design<br>
 More work with locking. With only one exception all locking and unlocking is initiated via javascript<br>
 Minor fix to copycontent
</li>
<li>2015-09-06 v1.0<br>
 Initial public release
</li>
</ul>
